name: qrcodesample
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  qr_code_scanner: ^1.0.1 # Check for the latest version on pub.dev

flutter:
  uses-material-design: true
